apiVersion: v1
kind: Service
metadata:
  name: redis-ip-service
  labels:
    app: deployed-app
spec:
  ports:
   - port: 6379
     targetPort: 6379
  selector:
    app: deployed-app
    name: redis-pod
  