apiVersion: v1
kind: Service
metadata:
  name: load-balancer-service
  labels:
    app: deployed-app

spec:
  type: LoadBalancer
  ports:
   - port: 8000
     targetPort: 8000
  selector:
     app: deployed-app
     name: app-pod