apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-pod
  labels:
    app: deployed-app
    name: redis-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployed-app
      name: redis-pod 
  template:
    metadata:
      name: redis-pod
      labels:
        app: deployed-app
        name: redis-pod
    spec:
      containers:
        - name: redis
          image: gcr.io/newproject-final/redis-image 
          ports:
            - containerPort: 6379